---
development:
  cloud_name: carte-territoire
  api_key: '168578886933586'
  api_secret: "-E0yCu2AqzVoO_5ypt1um_G6xK0"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: carte-territoire
  api_key: '168578886933586'
  api_secret: "-E0yCu2AqzVoO_5ypt1um_G6xK0"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: carte-territoire
  api_key: '168578886933586'
  api_secret: "-E0yCu2AqzVoO_5ypt1um_G6xK0"
  enhance_image_tag: true
  static_file_support: false
